// eslint-disable-next-line no-undef
module.exports = {
    siteName: "KevinK.dev",
    siteAuthor: "@Unkn0wnKevin",
    siteURL: "https://kevink.dev",
    payPalMail: "kevin@1in9.net",
    siteKeywords:
        "Kevin Kandlbinder, Kevin, Kandlbinder, Web, Web Developer, Developer, JavaScript, PHP, Java, Photos, Fotos",
    iconPath: "src/images/fullbglogo@10x.png",
    languages: ["en", "de"],
    contactEmail: "kevin@kevink.dev",
    contactPhone: "+4941068068004",
    address: "25451 Quickborn, Schleswig-Holstein, Germany",
    mapsLink: "https://goo.gl/maps/KVq9z1PVaVP2",
    contactTwitter: "Unkn0wnKevin",
    contactGitHub: "Unkn0wnCat",
    contactMastodon: "@kevin@1in1.net",
    contactMastodonHref: "https://mastodon.1in1.net/@kevin",
    givenName: "Kevin",
    familyName: "Kandlbinder",
    birthDate: "2001-03-11",
    gender: "Male",
    height: "168 cm",
    nationality: "Germany",
    personImage: "./content/images/kevin-kandlbinder-04.jpg",
    sameAs: [
        "https://mastodon.1in1.net/@kevin",
        "https://github.com/Unkn0wnCat",
        "https://unkn0wncat.net/",
        "https://twitter.com/@Unkn0wnKevin",
        "https://unsplash.com/@unkn0wncat",
    ],
};
