export const contactLink: string;
export const contactLinks: string;
export const friendBg: string;
export const friendBio: string;
export const friendImage: string;
export const friendName: string;
export const friendProfile: string;
export const friendsList: string;
export const friendTitle: string;
