name: Build Site

on:
  push:

jobs:
  update:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - run: npm install
      name: Install Dependencies

    - run: npm run build
      name: Build Site
        
    - uses: actions/upload-artifact@v2
      name: Upload Artifacts
      with:
        name: site
        path: public
